Feature/add eum
LucasAlegre/morl-baselines pull request #23
Opened 2023-01-26 11:42 UTC by ffelten

2023-01-26 13:48 UTC, LucasAlegre commented
The only strange thing to me is that it receives the `utility = np.dot` as a parameter. I can not think of a use case where someone will pass a weight list, but not use np.dot.

2023-01-26 13:51 UTC, LucasAlegre requested changes

2023-01-26 13:51 UTC, LucasAlegre commented on morl_baselines/common/performance_indicators.py
> +def eum(front: List[np.ndarray], weights_set: np.ndarray, utility: Callable = np.dot) -> float:
I would name the function `expected_utility`, as many people don't know the EUM abbreviation.

2023-01-26 13:54 UTC, ffelten commented
> The only strange thing to me is that it receives the `utility = np.dot` as a parameter. I can not think of a use case where someone will pass a weight list, but not use np.dot.

In the case the user's utility follows a non linear setting.

2023-02-01 08:28 UTC, LucasAlegre approved these changes

2023-02-01 08:29 UTC, merged