Unify evaluation metrics across all algorithms
LucasAlegre/morl-baselines pull request #36
Opened 2023-02-23 10:18 UTC by ffelten

Relates to #12

2023-03-06 10:45 UTC, ffelten commented
- [ ] wait for MO-Gymnasium latest release with `pareto_front` computations

2023-03-08 14:19 UTC, LucasAlegre requested changes

2023-03-08 14:19 UTC, LucasAlegre commented on morl_baselines/common/utils.py
> +        current_front, weights_set=get_reference_directions("energy", reward_dim, n_sample_weights).astype(np.float32)
you can call equally_space_weights instead

2023-03-08 14:19 UTC, LucasAlegre commented on morl_baselines/common/utils.py
> +    n_sample_weights: int = 20,
I'd default it to 50 or 100

2023-03-08 14:19 UTC, LucasAlegre commented on morl_baselines/multi_policy/envelope/envelope.py
>              if eval_env is not None and self.log and self.global_step % eval_freq == 0:
I think we need to change this to log the front every "iteration", instead of every eval_freq, similarly as in GPI-PD

2023-03-14 16:54 UTC, merged